pipelines/urls.py
from django.urls import path
from . import views
from .extra_logic import *
from django.views.generic.base import TemplateView
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', views.ReportList, name='index'),
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('reports/', views.ReportList, name='report_list'),
    path('map/', TemplateView.as_view(template_name='gas_survey.html')),
    path('reportview/<int:survey_id>/', views.ReportView, name='report_view'),
    path('createreport/', views.CreateReport, name='create_report'),
    path('editreport/<survey_id>/', views.EditReport, name='edit_report'),
    path('editreport/<survey_id>/addleak', views.AddLeak, name='add_leak'),
    path('editreport/<survey_id>/<leak_id>/', views.DeleteLeak, name='delete_leak'),
    path('repair/<survey_id>/<leak_id>/', mark_repaired, name='mark_repaired'),
    path('undorepair/<survey_id>/<leak_id>/', mark_not_repaired, name='undo_repaired'),
    path('password/', views.change_password, name='change_pw'),
    path('gasupload/', views.GasUpload, name='gasupload'),
    path('gaspointAPI/', views.GasPointAPI.as_view()),
    path('extract/<inf_id>', views.EditSite, name='tileupload'),
    path('infrastructure_list/', views.ListInfrastructure, name='infrastructure_list'),
    path('JSONupload/', views.UploadJSON, name='jsonupload'),
    path('terms/', TemplateView.as_view(template_name='terms.html'), name='terms'),
    path('privacy/', TemplateView.as_view(template_name='privacy.html'), name='privacy'),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ssec_portal/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import index_redirect
from django.conf import settings # new
from django.conf.urls.static import static # new

urlpatterns = [
    path('', index_redirect),
    path('pipelines/', include('pipelines.urls')),
    path('admin/', admin.site.urls),
    path('pipelines/', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pipelines/models.py
from django.contrib.gis.db import models
from django.contrib.auth.models import AbstractUser
from django.contrib.postgres.fields import JSONField


# Create your models here.


class Client(models.Model):
    client_id = models.AutoField(primary_key=True)
    client_company = models.CharField(max_length=70)
    client_email = models.CharField(max_length=70)
    client_phone = models.CharField(max_length=10, null=True)

    def __str__(self):
        return "{}".format(self.client_company)


# add company ID field to the User model to pair with Client table.
class CustomUser(AbstractUser):
    client_id_fk = models.ForeignKey(Client, on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return self.email


class Pipeline(models.Model):
    client_id_fk = models.ForeignKey(Client, on_delete=models.CASCADE, null=True)
    pipe_name = models.CharField(max_length=20)
    pipe_geom = models.LineStringField(null=True)

    def __str__(self):
        return self.pipe_name


class Infrastructure(models.Model):
    inf_id = models.AutoField(primary_key=True)
    client_id_fk = models.ForeignKey(Client, on_delete=models.CASCADE)
    inf_name = models.CharField(max_length=35)
    inf_geom = models.PointField(null=True)
    inf_tile_url = models.CharField(null=True, max_length=100, blank=True)

    def __str__(self):
        return self.inf_name


class SurveyDate(models.Model):
    GEOMETRY_CHOICES = (
        ("PIPELINE", "Pipeline"),
        ("SITE", "Site"),
    )
    client_id_fk = models.ForeignKey(Client, on_delete=models.CASCADE, related_name='surveys')
    pipe_id_fk = models.ForeignKey(Pipeline, null=True, on_delete=models.CASCADE, blank=True)
    survey_date = models.DateField()
    inf_id_fk = models.ForeignKey(Infrastructure, null=True, on_delete=models.CASCADE, blank=True)
    geometry_type = models.CharField(max_length=8, choices=GEOMETRY_CHOICES)
    wind_direction = models.CharField(max_length=3, null=True, blank=True )
    temperature = models.IntegerField(null=True, blank=True)
    flight_duration = models.CharField(max_length=10, null=True, blank=True,)
    survey_comments = models.TextField(null=True, blank=True)
    survey_complete = models.BooleanField(default=False)
    survey_gas_point_geom = models.MultiPointField(null=True, blank=True, srid=4326, dim=3)
    survey_gas_poly_geom = models.PolygonField(null=True, blank=True, srid=4326)
    survey_contour_geom = JSONField(default="{}")


    def __str__(self):
        return "{} | {}".format(str(self.survey_date), str(self.inf_id_fk))


class SurveyPoint(models.Model):
    surveydate_id_fk = models.ForeignKey(SurveyDate, on_delete=models.CASCADE, related_name="surveypoint", null=True)
    gas_value = models.FloatField()
    gas_geom = models.PointField(null=True)
    gas_lat = models.CharField(max_length=50, null=True)
    gas_long = models.CharField(max_length=50, null=True)

    def __str__(self):
        return str(self.gas_value)


class Deficiency(models.Model):
    surveydate_id_fk = models.ForeignKey(SurveyDate, on_delete=models.CASCADE, related_name="surveydef")
    deficiency_number = models.IntegerField()
    deficiency_gas = models.FloatField()
    deficiency_desc = models.TextField(null=True, blank=True)
    deficiency_photo = models.ImageField(upload_to='images', null=True,
                                         blank=True)  # link to image uploaded to photos folder
    deficiency_thermal = models.ImageField(upload_to='images', null=True,
                                           blank=True)  # spot for thermal images in future
    deficiency_repaired = models.BooleanField(default=False)
    deficiency_signoff = models.ForeignKey(CustomUser, null=True, blank=True, on_delete=models.PROTECT,
                                           related_name="inspector")
    deficiency_signoff_date = models.DateField(null=True, blank=True)

    def __str__(self):
        return str(self.deficiency_number)


# a table to keep track of all changes in case a user marks something as repaired when it wasn't and tries to change it
class DeficiencyHistory(models.Model):
    surveydate_id_fk = models.ForeignKey(SurveyDate, on_delete=models.CASCADE)
    history_leak_id = models.ForeignKey(Deficiency, on_delete=models.CASCADE, null=True, related_name='leakhistory')
    history_action = models.CharField(max_length=15)
    history_actor = models.ForeignKey(CustomUser, on_delete=models.PROTECT)
    history_date = models.DateField()

pipelines/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import generic
from django.contrib import messages
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from rest_framework.renderers import JSONRenderer
from rest_framework.views import APIView
from rest_framework.response import Response
from django.http import JsonResponse
from django.core.serializers import serialize
import datetime

from .forms import *
from .models import *
from .extra_logic import *


# Create your views here.


class SignUp(generic.CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'signup.html'


def index(request):
    return render(request, 'index.html')


def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Important!
            messages.success(request, 'Your password was successfully updated!')
            return redirect('index')
        else:
            messages.error(request, 'Please correct the error below.')
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'registration/change_password.html', {
        'form': form
    })


def ReportList(request):
    # form = SurveyDateForm(request)
    user = request.user
    try:
        client_id = request.user.client_id_fk
    except:
        client_id = 0
    report_list = []
    if user.is_superuser == True:
        reports = SurveyDate.objects.all()
    else:
        reports = SurveyDate.objects.filter(client_id_fk=client_id)
    for report in reports:
        # Check to see if there are any leaks
        leaks = report.surveydef.all()
        leak = 'none'
        leak_check = 0
        # check to see if there are any leaks. If so, assume repaired. If not repaired set variable to indicate leak.
        if len(leaks) > 0:
            leak = 'repd'
            for item in leaks:
                if item.deficiency_repaired == False:
                    leak_check += 1
        if leak_check > 0:
            leak = 'leak'
        complete = report.survey_complete
        if report.geometry_type == "PIPELINE":
            site_name = report.pipe_id_fk
        elif report.geometry_type == "SITE":
            site_name = report.inf_id_fk
        else:
            site_name = 'NA'
        report_list.append(
            {"name": site_name, "date": report.survey_date, "id": report.id, "company": report.client_id_fk,
             'complete': complete, 'leak': leak})

    context = {'report_list': report_list}
    # form.fields['pipe_id_fk'].queryset = SurveyDate.objects.filter(client_id_fk=client_id)

    return render(request, 'report-list.html', context)


def ReportView(request, survey_id):
    survey = SurveyDate.objects.get(pk=survey_id)
    request.session['survey_id'] = survey_id
    user = request.user
    if user.is_anonymous:
        return redirect('login')
    if user.client_id_fk == survey.client_id_fk or user.is_superuser == True:
        context = {}
        deficiencies = survey.surveydef.all()
        context['defs'] = deficiencies
        context['survey'] = survey
        geoms = []

        if survey.geometry_type == "PIPELINE":
            pipeline = Pipeline.objects.get(pk=survey.pipe_id_fk.id)
            name = survey.pipe_id_fk.pipe_name
            allcoords = [[coord[0], coord[1]] for coord in pipeline.pipe_geom.coords]
            context['points'] = geoms
            context['name'] = name
            context['linecoords'] = allcoords
            context['infcoords'] = []
        elif survey.geometry_type == "SITE":
            site = Infrastructure.objects.get(pk=survey.inf_id_fk_id)
            sitename = survey.inf_id_fk.inf_name
            coords = site.inf_geom.coords
            infcoords = [coords[0], coords[1]]
            context['points'] = geoms
            context['name'] = sitename
            context['linecoords'] = []
            context['infcoords'] = infcoords
            context['inf_image'] = site.inf_tile_url
        else:
            name = "Unknown Location"

        return render(request, 'report-view.html', context)
    else:
        return redirect('login')


def CreateReport(request):
    user = request.user
    if user.is_anonymous:
        return redirect('login')
    if not user.is_superuser:
        return redirect('index')
    if request.method == 'POST':
        header_form = CreateReportForm(request.POST)
        if header_form.is_valid():
            new_survey = header_form.save()
            survey_id = new_survey.id
            return redirect('edit_report', survey_id=survey_id)
    else:
        header_form = CreateReportForm()
    return render(request, 'create-report.html', {'header_form': header_form})


def EditReport(request, survey_id):
    user = request.user
    if user.is_anonymous:
        return redirect('login')
    if not user.is_superuser:
        return redirect('index')
    context = {'survey_id': survey_id}
    request.session['survey_id'] = survey_id
    survey_obj = SurveyDate.objects.get(pk=survey_id)
    context["survey"] = survey_obj
    deficiencies = survey_obj.surveydef.all()
    context['defs'] = deficiencies
    if request.method == 'POST':
        header_form = CreateReportForm(request.POST, instance=survey_obj)
        if header_form.is_valid():
            header_form.save()
            now = datetime.datetime.now()
            messages.add_message(request, messages.INFO, 'Last saved at {}'.format(now.strftime("%H:%M:%S")))
            return redirect('edit_report', survey_id=survey_id)
    else:
        header_form = CreateReportForm(instance=survey_obj)

    context['header_form'] = header_form

    return render(request, 'edit-report.html', context)


def AddLeak(request, survey_id):
    user = request.user
    if user.is_anonymous:
        return redirect('login')
    if not user.is_superuser:
        return redirect('index')
    context = {}

    if request.method == 'POST':
        form = LeakForm(request.POST, request.FILES, initial={'surveydate_id_fk': survey_id})
        if form.is_valid():
            form.save()
            return redirect('edit_report', survey_id=survey_id)
    else:
        form = LeakForm(initial={'surveydate_id_fk': survey_id})

    context['form'] = form

    return render(request, 'create-leak.html', context)


def DeleteLeak(request, survey_id, leak_id):
    user = request.user
    if not user.is_superuser:
        return redirect('index')

    leak = Deficiency.objects.get(pk=leak_id)
    leak.delete()

    return redirect('edit_report', survey_id=survey_id)

def GasUpload(request):
    from django.core.files.storage import FileSystemStorage
    from django.contrib.gis.geos import MultiPoint, Point
    import os
    survey_id = request.session['survey_id']
    survey = SurveyDate.objects.get(pk=survey_id)
    if request.method == "POST" and request.FILES['gasfile']:
        gasfile = request.FILES['gasfile']
        fs = FileSystemStorage()
        filename = fs.save(gasfile.name, gasfile)
        filename = os.path.join("media/", filename)
        with open (filename, 'r') as gas:
            gas = gas.readlines()
            gasdata = []
            for line in gas:
                if not line.startswith("L"):
                    line = line.strip().split(",")
                    lat, long, gasvalue = line[0], line[1], line[2]
                    gas_point = Point(x=float(long), y=float(lat), z=float(gasvalue))
                    gasdata.append(gas_point)
                else:
                    continue

            gas_mp = MultiPoint(gasdata)
            survey.survey_gas_point_geom = gas_mp
            survey.save()

        return redirect("edit_report", survey_id=survey_id)


    return render(request, "gasupload.html")


def UploadJSON(request):
    import os
    from django.core.files.storage import FileSystemStorage
    survey_id = request.session['survey_id']
    survey = SurveyDate.objects.get(pk=survey_id)
    if request.method == "POST" and request.FILES['jsonfile']:
        JSONfile = request.FILES['jsonfile']
        fs = FileSystemStorage()
        filename = fs.save(JSONfile.name, JSONfile)
        filename = os.path.join("media/", filename)
        with open (filename, 'r') as contours:
            contours = contours.readlines()
            contour_lines = ""
            for line in contours:
                line = line.strip()
                contour_lines += line

            survey.survey_contour_geom = contour_lines
            survey.save()
            print (survey.survey_contour_geom)

        return redirect("edit_report", survey_id=survey_id)


    return render(request, "JSONupload.html")


def EditSite(request, inf_id):
    from django.core.files.storage import FileSystemStorage
    from django.contrib.gis.geos import MultiPoint, Point
    import os, zipfile
    inf = Infrastructure.objects.get(pk=inf_id)
    if request.method == "POST" and request.FILES['tilefile']:
        tilefile = request.FILES['tilefile']
        fs = FileSystemStorage()
        tilename = fs.save(tilefile.name, tilefile)
        tilename = os.path.join("media/", tilename)
        unique_id = inf.inf_name.replace(" ", "")
        inf.inf_tile_url = 'media/tiles/{}'.format(unique_id)
        inf.save()

        with zipfile.ZipFile(tilename, 'r') as file:
            file.extractall(path='media/tiles/{}'.format(unique_id))
        return redirect('index')
    return render(request, "editsite.html")


def ListInfrastructure(request):
    all_infs = Infrastructure.objects.all()
    context = {"inf_list": Infrastructure.objects.all()}
    return render(request, "inf_list.html", context)



class GasPointAPI(APIView):

    renderer_classes = [JSONRenderer]

templates/create-leak.html
{% extends 'base.html' %}
{% load static %}
{% block headcontent %}
<title>Create Leak</title>

{% endblock %}

{% block content %}
{% if user.is_authenticated %}
{% if user.is_superuser %}
<h1>Add New Leak</h1>
    <form method="post" enctype="multipart/form-data">{% csrf_token %}
    <p><input type="submit" value="Save" class="button"></p>
    {{ form.as_p }}
</form>

{% endif %}
{% endif %}
{% endblock %}

templates/create-report.html
{% extends 'base.html' %}
{% load static %}
{% block headcontent %}
<title>Site Name Goes Here</title>

{% endblock %}

{% block content %}
{% if user.is_authenticated %}
{% if user.is_superuser %}
<h3>Create New Report</h3>
<hr>
<form method="post" id="create_form">{% csrf_token %}

    <table class="formtable">
        {% for field in header_form %}
            <tr>
                <th>{{ field.label_tag }}</th>
                <td>{{ field }}</td>
            </tr>
        {% endfor %}
    </table>
    <p><button type="submit" class="save-button" style="width:200px;">Save</button></p>
</form>
<script>
    var linkID = document.getElementById("create");
    linkID.className += "active";
</script>
{% endif %}
{% endif %}
{% endblock %}

templates/editsite.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<div id="tilefile">
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <h3>Upload Site Imagery</h3>
        <p><input type="file" name="tilefile" style="margin: 15px;"></p>
        <p><button type="submit" class="button">Upload Tiles</button></p>
    </form>
</div>

{% endblock %}

templates/gasupload.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<div id="gasfile">
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <p><input type="file" name="gasfile"></p>
        <p><button type="submit" class="button">Upload Gas File</button></p>
    </form>
</div>
{% endblock %}

templates/header.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
</head>
<body>

</body>
</html>

templates/index.html
{% extends 'base.html' %}

{% block content %}
<div class="body">
    Silver Spring Energy Consulting Ltd. provides this portal for our clients to access and review methane surveys
    performed along their pipelines.
</div>


{% endblock %}
{

templates/report-view.html
{% extends 'base.html' %}
{% load static %}
{% block headcontent %}

<!-- Leaflet CSS -->
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.5.1/dist/leaflet.css"
          integrity="sha512-xwE/Az9zrjBIphAcBb3F6JVqxf46+CDLwfLMHloNu6KEQCAWi6HcDUbeOfBIptF7tcCzusKFjFw2yuvEpDL9wQ=="
          crossorigin=""/>
    <!-- Leaflet JS. Make sure you put this AFTER Leaflet's CSS -->
    <script src="https://unpkg.com/leaflet@1.5.1/dist/leaflet.js"
            integrity="sha512-GffPMF3RvMeYyc1LWMHtK8EbPv0iNZ8/oTtHPx9/cc2ILxQ+u905qIwdpULaqDkyBKgOaB57QTMg7ztg8Jm2Og=="
            crossorigin=""></script>
    <script src="https://code.jquery.com/jquery-2.1.3.js"></script>
{% endblock %}

{% block content %}
{% if user.is_authenticated %}

<h2>Gas Survey Results  - Prepared for {{survey.client_id_fk}}</h2>
<hr>
<h4>Survey Date: {{survey.survey_date}}</h4>
<hr>
<table class="info-table">
    <tr>
        <th>Location: </th>
        <td>{{ name }} </td>
    </tr>
    <tr>
        <th>Location Type: </th>
        <td>{{survey.get_geometry_type_display}}</td>
    </tr>
    <tr>
        <th>Wind Direction: </th>
        <td>{{survey.wind_direction}}</td>
    </tr>
    <tr>
        <th>Temperature: </th>
        <td>{{survey.temperature}}</td>
    </tr>
    <tr>
        <th>Flight Duration: </th>
        <td>{{survey.flight_duration}}</td>
    </tr>

</table>

<p><b>&nbsp;Comments:</b></p>
<p>{{survey.survey_comment}}</p>
<hr>

<h3>Map of Findings</h3>
<div id="map"></div>
<hr>

<h3>Possible Leaks</h3>
<table class="data-table">
    <tr class="header">
        <th>Tag Number</th>
        <th>Gas Reading</th>
        <th>Photo</th>
        <th>Status</th>
       <th>Signoff Date</th>
        <th></th>
    </tr>
    {% for def in defs %}
    <tr>
        <td>{{def.deficiency_number}}</td>
        <td>{{def.deficiency_gas}}</td>
        <td><img id="{{def.deficiency_number}}" src="{{def.deficiency_photo.url}}" style="width:75px;"></td>
        <td>{% if not def.deficiency_repaired %}Ongoing{% else %}Repaired by: <br>{{def.deficiency_signoff}}{% endif %}</td>
        <td>{{def.deficiency_signoff_date}}</td>
        {% if not def.deficiency_repaired %}
        <td><a href="{% url 'mark_repaired' def.surveydate_id_fk.id def.id %}" class="button">Mark Repaired</a></td>
        {% else %}
        <td><a href="{% url 'undo_repaired' def.surveydate_id_fk.id def.id %}" class="red-button">Undo Repaired</a></td>
        {% endif %}

        <!-- The Modal -->
        <div id="myModal{{def.deficiency_number}}" class="modal">

            <!-- The Close Button -->
            <span class="close{{def.deficiency_number}}"
                  style="position:absolute;top:15px;right:35px;color:#f1f1f1;font-size:40px;font-weight:bold;transition:0.3s;">&times;</span>

            <!-- Modal Content (The Image) -->
            <img class="modal-content" id="img0{{def.deficiency_number}}">

        </div>
        <script>
    // Get the modal
    var modal = document.getElementById("myModal{{def.deficiency_number}}");

    // Get the image and insert it inside the modal - use its "alt" text as a caption
    var img = document.getElementById("{{def.deficiency_number}}");
    var mapDiv = document.getElementById("map");
    var modalImg = document.getElementById("img0{{def.deficiency_number}}");
    // var captionText = document.getElementById("caption");
    img.onclick = function(){
      modal.style.display = "block";
      modalImg.src = this.src;
      // hide the map
      mapDiv.style.display = 'none';
    }

    // Get the <span> element that closes the modal
    var span = document.getElementsByClassName("close{{def.deficiency_number}}")[0];

    // When the user clicks on <span> (x), close the modal
    span.onclick = function() {
      modal.style.display = "none";
      mapDiv.style.display = "block";
    }
        </script>
    </tr>
    <tr>
        <td colspan="3">{{def.deficiency_desc}}</td>
    </tr>
    {% endfor %}
</table>



<script>

{% block jquery %}
    var endpoint = "/pipelines/gaspointAPI/"
    $.ajax({
        method: "GET",
        url: endpoint,
        dataType: 'json',
        success: function(data) {


            // Bring in JSON data
            var gasdata = [{
                "type": "FeatureCollection",
                "name": "{{ name }}",
                "crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
                "features": [
                    {"type": "Feature", "geometry": { "type": "MultiPoint", "coordinates": data
                }}]
            }];

            var contourdata = [{{ survey.survey_contour_geom | safe }}];

            var sitetype = '{{ survey.geometry_type | safe }}';

            if (sitetype == "PIPELINE") {
                var site_geo = '{{ linecoords | safe }}';
            } else {
                var site_geo = '{{ infcoords | safe }}';
            };
            console.log(site_geo);


            // Initialize map container
            var gasmap = L.map('map', {maxZoom: 20}).setView([53, -115], 6);


            // Create functions for styling gas points and contours
            var i = 0

            function PointColor (gasvalue) {
                if (gasvalue > 1000) {
                    i ++;
                    return '#800026';
                } else if (gasvalue > 750) {
                    i ++;
                    return '#BD0026';
                } else if (gasvalue > 500) {
                    i ++;
                    return '#E31A1C';
                } else if (gasvalue > 250) {
                    i ++;
                    return '#FC4E2A';
                } else if  (gasvalue > 125) {
                    i ++;
                    return '#FD8D3C';
                } else if (gasvalue > 75) {
                    i ++;
                    return '#FEB24C';
                } else if ( gasvalue > 10) {
                    i ++;
                    return '#FED976';
                } else {i ++; return '#FFEDA0';}
            }

            function gasstyle (feature) {
                return {
                    // color: PointColor(feature.geometry.coordinates[i]),
                    fillColor: PointColor(feature.geometry.coordinates[i][2]),
                    weight: "0",
                    radius: "5",
                    fillOpacity: "1"
                }
            }

            function contour_style (feature) {
                return {
                color: PointColor(feature.properties.GAS),
                weight: 2
                }
            }


            // Add data layers to map
            var gaslayer = L.geoJson(gasdata, {
                pointToLayer: function (feature, latlng) {
                    return L.circleMarker(latlng, gasstyle(feature))
                    }
            });

            var contourlayer = L.geoJson(contourdata, {style: contour_style}).addTo(gasmap);

            /*
            function PickSite (sitetype) {
                if sitetype == 'SITE'
                return L.
            }*/

            try {
                gasmap.fitBounds(gaslayer.getBounds());
            }
            catch {
                // gasmap.fitBounds(sitelayer.getBounds());
            }


            // Add mapbox basemaps as a group so they can be properly added to the layer control
            var mapbox = ({
                'Streets': L.tileLayer('https://api.tiles.mapbox.com/v4/mapbox.streets/{z}/{x}/{y}.png?access_token=pk.eyJ1Ijoia3B1YmJlbiIsImEiOiJjanV1NnZudngwZnR6M3lwaGxzemd6MjE3In0.9bfM9SkEGnTZJN11T3FoOw'
                                    ).addTo(gasmap)
                });


            // Add site imagery
            imagery = L.tileLayer('http://127.0.0.1:8000/pipelines/{{ inf_image }}/{z}/{x}/{y}.png', {tms: true, maxZoom: 20}).addTo(gasmap)


            L.control.scale().addTo(gasmap);

            // Add legend for gas color ramp
            var legend = L.control({position: 'bottomright'});

                legend.onAdd = function (gasmap) {

                    var div = L.DomUtil.create('div', 'info legend'),
                        grades = [0, 10, 75, 125, 250, 500, 750, 1000],
                        labels = [];

                    // loop through our density intervals and generate a label with a colored square for each interval
                    div.innerHTML += '<p>Methane (PPMM)</p>'
                    for (var k = 0; k < grades.length; k++) {
                        div.innerHTML +=
                            '<i style="background:' + PointColor(grades[k] + 1) + '"></i> ' +
                            grades[k] + (grades[k + 1] ? '&ndash;' + grades[k + 1] + '<br>' : '+');
                    }

                    return div;
                };

                legend.addTo(gasmap);


                // Add layer control
                var maplayers = {
                    "Gas Survey": gaslayer,
                    "Gas Trends": contourlayer,
                    "Site Imagery": imagery
                }

                group = L.control.layers(null, maplayers, {collapsed: false}).addTo(gasmap)

            // change leaflet attribution to custom
            document.getElementsByClassName('leaflet-control-attribution')[0].innerHTML = 'Powered by Leaflet<br>&copy; Silver Spring Energy Consulting Ltd.';
            document.getElementsByClassName('leaflet-control-attribution')[0].style.textAlign = 'right';
            }
    })
{% endblock %}
</script>
{% else %}
<p>You must be <a href="#">logged in</a> to see this data</p>
{% endif %}
{% endblock %}

templates/signup.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'signupcss.css' %}">
<h2>Sign up</h2>

<p>If you would like an account with us please sign up using the form below. One of our staff will contact you to link
your account with the appropriate corporate account.</p>


<form method="post">
  {% csrf_token %}
  {{ form.as_ul }}
  <button type="submit">Sign up</button>
</form>
{% endblock %}